### PR TITLE
Fix default codegen version

### PR DESCRIPTION
**Pull request by mbohlool**
Default codegen version was set to an unreleased version 2.3.0. Setting it to the latest version 2.2.3.

### CODE REVIEW

**Comment by mbohlool** [comment]
@lwander I changed the PR after your LGTM. PTAL.

**Comment by brejoc** [comment]
@mbohlool  LGTM. But in #319 you asked me to run it with version 2.2.2, not 2.2.3.

**Comment by mbohlool** [comment]
@brejoc I restricted python codegen version in the next commit in `python.sh` file.

**Comment by mbohlool** [comment]
@lwander @brejoc Thanks for the review.

**Pull request merged**
