### PR TITLE
Cleanup XML file.

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by mbohlool** [comment]
I guess this needs a rebase?

**Comment by mbohlool** [comment]
This PR still have one of my old commits. If you review that commit we can merge them both or you can remove it from this PR and I will send a new PR for it.

**Comment by brendandburns** [comment]
Roger that, I will rebase.

**Comment by brendandburns** [comment]
Looks like this should wait for #9 to merge then I'll rebase again...

**Comment by mbohlool** [comment]
Can you rebase this?

**Comment by brendandburns** [comment]
Rebased.

**Comment by mbohlool** [comment]
There is still one dummy commit (update readme by me). Can you drop that? Prefer not to have that in the repo.

**Comment by mbohlool** [comment]
friendly ping.

**Comment by brendandburns** [comment]
Fixed, sorry for the delay...

**Comment by mbohlool** [comment]
Np.

**Pull request merged**
