### PR TITLE
switched openapi generator to latest v5.1.0

### PR DESCRIPTION
**Pull request by yliaog**
Fixes https://github.com/kubernetes-client/python/issues/1421

latest openapi generator release is v5.1.0 (https://github.com/OpenAPITools/openapi-generator)

### CODE REVIEW

**Comment by roycaihw** [comment]
Thanks for holding. I'd like to keep our in-flight v17 Python client releases using the same client generator version. It would be great if we can merge this after we.

But technically we should be able to configure the value in the Python repo, so we can merge this if other clients need this.

**Comment by brendandburns** [comment]
/approve

But I think the best practice is for each client library to specify their own commit hash so that the behavior is deterministic per-library.

**Comment by brendandburns** [comment]
@roycaihw let me know when this is ready to merge (or just un-hold it yourself)

**Comment by yue9944882** [comment]
+1 bumping generator for java

**Comment by roycaihw** [comment]
/hold cancel

Sorry for the late reply. The python client release doesn't block this.

**Pull request merged**
