### PR TITLE
Switch to the slim maven Docker base image, significantly faster pulls

### PR DESCRIPTION
**Pull request by brendandburns**
@mbohlool

### CODE REVIEW

**Comment by tg123** [comment]
cherry-pick and test on autorest, failed.

```
[INFO] VERBOSE: [FYI- npm does not currently support progress... this may take a few moments]
[INFO] VERBOSE: Running  npm install for @microsoft.azure/autorest.csharp, 2.2.41
[INFO] VERBOSE: npm install completed @microsoft.azure/autorest.csharp, 2.2.41
[INFO]    Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.31)
[INFO] FailFast: Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
[INFO]
[INFO]    at System.Environment.FailFast(System.String)
[INFO]    at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
[INFO]    at System.Globalization.GlobalizationMode..cctor()
[INFO]    at System.Globalization.CultureData.CreateCultureWithInvariantData()
[INFO]    at System.Globalization.CultureData.get_Invariant()
[INFO]    at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
[INFO]    at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean)
[INFO]    at System.Globalization.CultureInfo.Init()
[INFO]    at System.Globalization.CultureInfo..cctor()
[INFO]    at System.StringComparer..cctor()
[INFO]    at System.AppDomainSetup.SetCompatibilitySwitches(System.Collections.Generic.IEnumerable`1<System.String>)
[INFO]    at System.AppDomain.PrepareDataForSetup(System.String, System.AppDomainSetup, System.Security.Policy.Evidence, System.Security.Policy.Evidence, IntPtr, System.String, System.String[], System.String[])
[INFO] Error: read ECONNRESET
[INFO]     at _errnoException (util.js:1024:11)
[INFO]     at Pipe.onread (net.js:615:25)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by mbohlool** [comment]
@brendandburns @tg123 are you guys looking for a fix for autorest? Or should we close this?

**Comment by brendandburns** [comment]
I'm going to fix this...

--brendan

________________________________

**Comment by brendandburns** [comment]
Ok PR updated to include the dotnet dependencies.  AutoRest works correctly now in this docker image.

**Comment by tg123** [comment]
LGTM tested generated file

**Comment by mbohlool** [comment]
LGTM

**Pull request merged**
