### PR TITLE
Switch to JDK date time library

### PR DESCRIPTION
**Pull request by dsyer**
Please do not merge until we finish discussing in the Java 
client tracker.

See https://github.com/kubernetes-client/java/issues/1411

### CODE REVIEW

**Comment by dsyer** [comment]
This can (and should) be merged now that the Java client is using JDK time on master: https://github.com/kubernetes-client/java/pull/1418

**Comment by synox** [comment]
The pom of release 11.0.0 still contains `joda-time`, see https://search.maven.org/artifact/io.kubernetes/client-java-api/11.0.0/bundle

**Comment by dsyer** [comment]
11.0.0 was released before this change. 12.0.0 will be the first release with JDK time I think. But I suppose that means you can't use the generator from master for a project that depends on 11.0.x? I don't know how to solve that - you probably have to use a tag or a fixed commit ID for the generator.

**Pull request merged**
