### PR TITLE
update scripts to download and run protoc for java over all k8s apis

### PR DESCRIPTION
**Pull request by cliveseldon**
#31

### CODE REVIEW

**Comment by brendandburns** [comment]
@cliveseldon thanks for doing the PR! Have you tried regenerating the protos and compiling the code in the Java project?

**Comment by cliveseldon** [comment]
Yes I've run it and it seems to work. It would be good to get some review by those who know the naming conventions for the generate.sh additions. I have left the class V1 the same and done some simple capitalizations for the other Java proto classes.
There is also the assumption that all these generated.proto files are always under master in the project /api following what was previously there for the V1 generated proto and class. I don't know enough about the apimachinary to know if this is valid.

**Comment by brendandburns** [comment]
Sorry for the delay here, I want to try to patch and run this myself and make sure everything still works and I haven't found the time...  I will try to get to this by the end of the week.

**Comment by cliveseldon** [comment]
That sounds great.

**Comment by brendandburns** [comment]
Validated that this seems to work correctly.  LGTM.

Thanks for the PR (and the patience!)

**Pull request merged**
