### PR TITLE
Revert "Revert "Initial add of a dotnet (C#) generator""

### PR DESCRIPTION
**Pull request by mbohlool**
Reverts kubernetes-client/gen#4

`AutoRest` has been approved by sig-api-machinery for dotnet client.

### CODE REVIEW

**Comment by mbohlool** [comment]
@brendanburns I am reverting my revert :) Let me know if you want to merge this version or you want to change anything. I will work on containerizing generation process and in that process you guys may want to tweak it for AutoRest.

**Comment by mbohlool** [comment]
@brendanburns friendly ping. I think we better name these files sharp.* because of the name of the repo.

**Comment by brendandburns** [comment]
SG, do you want merge this revert and then I'll rename the files? Or do you want to just rename them in this PR?

(btw, I think you mean `csharp.*` right?)

Thanks!

**Comment by mbohlool** [comment]
yes I meant `csharp.*`. I suggest we rename them in this PR (or resend the original PR with correct names) because it is easy enough.

**Comment by brendandburns** [comment]
sg, if you're willing to rename in this PR, go ahead and do that and then feel free to self-merge this PR.

Thanks!
--brendan

**Comment by mbohlool** [comment]
Done.

**Pull request merged**
