### PR TITLE
Script to generate haskell client

### PR DESCRIPTION
**Pull request by guoshimin**

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM, @mbohlool want to create a haskell repo?

**Comment by mbohlool** [comment]
@guoshimin @brendandburns I've created the repo and populated it with initial files and code of conduct and initial issues people can pick up to start developing. Also I generated first version of the client and this is the PR for it: https://github.com/kubernetes-client/haskell/pull/7

Please take a look at that.

Also @guoshimin do you want to be the owner of the haskell client and drive it forward?

**Comment by guoshimin** [comment]
@mbohlool Yeah I would love to.

**Comment by brendandburns** [comment]
I'm happy to help as well.

--brendan

________________________________

**Pull request merged**
