### PR TITLE
Add hideGenerationTimestamp & library options for Java

### PR DESCRIPTION
**Pull request by abelsromero**
This PR exposes the `hideGenerationTimestamp` and `library`.
Given the limitation for the cli options, I used `h`for `hideGenerationTimestamp` and `i` for `library`.

### CODE REVIEW

**Comment by brendandburns** [comment]
Seems reasonable, can I ask the use case?

**Review by yue9944882 — COMMENTED** [review]
/lgtm

i think it's meant for a minimal change/diff upon every code-generation

**Comment by abelsromero** [comment]
> Seems reasonable, can I ask the use case?

The way it is configured now, each model class adds an annotation with the genration timestamp like this:

```java
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-26T14:22:20.823Z[Etc/UTC]")
```

This makes that even a minimal change in a CRD involves changes to all model classes. This adds steps when reviewing the generated code, for example if you are commiting it and don't want to commit unmodified classes.
By adding the option to remove the timestamp (note the current default respects the previous logic) it means that only really modified model classes contain changes.


The change for `library` (default value also respect current value) is to users can use other implementations for the api to avoid extra dependencies or just personal preference. Currently it uses okhttp+gson, and for example some users may want to use resttemplate+jackson if they are in a Spring application.

**Comment by brendandburns** [comment]
/lgtm
/approve

(it's worth noting that there's little compatability between generators, so in practice I suspect that there will be challenges in changing generators, but there's no harm in adding it)

**Comment by abelsromero** [comment]
> (it's worth noting that there's little compatability between generators, so in practice I suspect that there will be challenges in changing generators, but there's no harm in adding it)

In fact I've been seeing that, in this case, this does not affect the generic generator but the custom CRD generator that is only present in JAVA. It's odd however, only Java has that.

**Pull request merged**
