### PR TITLE
Switch ruby client to use openapi-generator

### PR DESCRIPTION
**Pull request by ackintosh**
- Related issue : https://github.com/kubernetes-client/gen/issues/93
- Similar PR on the python client : https://github.com/kubernetes-client/gen/pull/97

### CODE REVIEW

**Comment by ackintosh** [comment]
There're hand-written test codes in `spec` folder, which is deleted on regeneration. 

[The hand-written tests is deleted on re-generation · Issue #29 · kubernetes-client/ruby](https://github.com/kubernetes-client/ruby/issues/29)

**Comment by brendandburns** [comment]
close/re-open to trigger CLA bot.

@ackintosh thanks for doing this. I LGTM'd your other PR.

/lgtm
/approve

**Comment by ackintosh** [comment]
@brendandburns Thanks for your merging. I'll file a PR to kubernetes-client/ruby to update the client.

**Comment by cjwagner** [comment]
/hold
Holding this PR because it is a draft PR and is causing problems with Tide.

**Comment by brendandburns** [comment]
@ackintosh can you remove the 'draft' label?

Thanks!

**Comment by ackintosh** [comment]
Thanks for notifying me! Made this PR to ready.

**Comment by ackintosh** [comment]
Thanks for merging this PR. As a next step to migrate to openapi-generator, I'll file a PR to kubernetes-client/ruby in order to update the Ruby client.

**Pull request merged**
