### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mbohlool**

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM.

**Comment by brendandburns** [comment]
@mbohlool if you make me an owner on this repo, I will merge your PRs :)

**Comment by mbohlool** [comment]
@brendandburns I've sent you the invite long ago (with write access). Let me know if you can't find the link and I will send it through PM.

**Comment by brendandburns** [comment]
Ah sorry must have missed my focused inbox...

I'll go looking for it.

Thanks!

--brendan

________________________________

**Pull request merged**
